### ISSUE TITLE
Failure of product when scrolling down when Event file is loaded

### ISSUE THREAD

**Issue by deadmanhunter** [sanbornst/CS4500-Group7#11]
System: Windows 8.1

Steps to reproduce:

Open MindReader
Load a binary or IBI file, and change window size so that the scroll bar appears.
Load a Comment file
Attempt to scroll down in the screen

Effect: 
Disruption of graphs, graphs overlay each other, and 'synch summary' displays on the screen, here is a screenshot:
![screenshot 10](https://cloud.githubusercontent.com/assets/6432916/7262750/ec307d02-e849-11e4-9e7d-493cadb858e5.png)

**Comment by sanbornst** [comment]
Fixed by disabling error bars on event files with only one point.
