### ISSUE TITLE
Graph export cuts off about 1/3 of the selected graph display

### ISSUE THREAD

**Issue by deadmanhunter** [sanbornst/CS4500-Group7#13]
Problem:
The export cuts off about 1/3rd of the graphs x axis range

Steps to reproduce:
Open the product
Load a binary file
set a stable zoom (say 300-400)
Export the graph
Compare to the graph in the application.

You will see a fair bit of the graph is cut off in the exported file.

**Comment by jordanreedie** [comment]
I'm going to close this and open up a more specific issue
